name: PlatformIO CI

on: [push]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Cache PlatformIO
        uses: actions/cache@v4
        with:
          path: ~/.platformio
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
      - name: Set up Python
        uses: actions/setup-python@v5
      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade platformio
      - name: PIO Check
        run: pio check --fail-on-defect high --skip-packages

  test_native:
    runs-on: ubuntu-latest
    needs: check
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Cache PlatformIO
        uses: actions/cache@v4
        with:
          path: ~/.platformio
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
      - name: Set up Python
        uses: actions/setup-python@v5
      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade platformio
      - name: PIO Test
        run: pio test -e native

  build_native:
    runs-on: ubuntu-latest
    needs: [check, test_native]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Cache PlatformIO
        uses: actions/cache@v4
        with:
          path: ~/.platformio
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
      - name: Set up Python
        uses: actions/setup-python@v5
      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade platformio
      - name: PIO Build
        run: pio run -e native

  build_example01:
    runs-on: ubuntu-latest
    needs: [check, test_native]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Cache PlatformIO
        uses: actions/cache@v4
        with:
          path: ~/.platformio
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
      - name: Set up Python
        uses: actions/setup-python@v5
      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade platformio
      - name: PIO Build
        run: pio ci examples/example-01/example-01.ino --lib . --project-conf examples/platformio.ini
  
  build_arduino_examples:
    runs-on: ubuntu-latest
    needs: [check, test_native]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Cache Arduino dependencies
        uses: actions/cache@v4
        with:
          path: ~/.arduino15
          key: ${{ runner.os }}-arduino
          restore-keys: |
            ${{ runner.os }}-arduino-
      - name: Cache Arduino Libraries
        uses: actions/cache@v4
        with:
          path: ~/Arduino
          key: ${{ runner.os }}-arduinolibs-
          restore-keys: |
            ${{ runner.os }}-arduinolibs-
      - uses: arduino/compile-sketches@v1
        with:
          fqbn: "esp32:esp32:esp32"
          enable-deltas-report: true
          enable-warnings-report: true
          platforms: |
            - name: "esp32:esp32"
          libraries: |
            - source-path: ./
            - name: MsgPack